---
- name: Implementing when conditions
  hosts: all
  vars:
    - a: 20
  tasks:
    - name: Download jenkins.war
      get_url:
        url: https://get.jenkins.io/war-stable/2.462.3/jenkins.war
        dest: /tmp
      when: a == 10 
