---
- name: Configuring tomcat using lopps
  hosts: all
  tasks:
    - name: Install  tocmat10 and tomcat10-admin
      apt:
        name: "{{item.a}}"
        state: "{{item.b}}"
        update_cache: "{{item.c}}"
      with_items:
        - {a: tomcat10,b: present,c: yes}
        - {a: tomcat10-admin,b: present,c: no}
    - name: Copy cusotmised tomcat-users.xml file
      copy:
        src: tomcat-users.xml
        dest: /etc/tomcat10
    - name: Change port of tomcat from 8080 to 9090
      replace:
        regexp: 8080
        replace: 9090
        path: /etc/tomcat10/server.xml
    - name: Restart tomcat10
      service:
        name: tomcat10
        state: restarted
    - name: Pause for 30 seconds
      pause:
        seconds: 30
    - name: Check tomcat on all servers
      uri:
        url: "{{item}}"
        status_code: 200
      with_items:
        - http://172.31.44.93:9090
        - http://172.31.37.179:9090
...








