- name: Create a user on all servers
  hosts: dbserver
  tasks:
    - name: Create a user
      user:
        name: Radha
        password: intelliqit
        uid: 2222
        shell: /bin/bash
        comment: "regular user"
        home: /tmp/Radha
...
